language: java
jdk:
  - openjdk6
env:
  - MAVEN_OPTS="-XX:PermSize=256m -XX:MaxPermSize=512m -Xmx1024m"
before_install:
  - mysql -e "CREATE DATABASE kune_dev;"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON kune_dev.* TO kune@localhost IDENTIFIED BY 'db4kune';"
  - mysql -e "ALTER DATABASE kune_dev CHARACTER SET utf8 DEFAULT CHARACTER SET utf8 COLLATE utf8_bin DEFAULT COLLATE utf8_bin;"
  - mysql -u root kune_dev < src/main/resources/db/kune_initialize.sql
install: true
script: mvn assembly:assembly -P production
